// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		int rcounter = 0;
		int repeatm = 0;
		int repeatl = 0;
		double nrandom = Math.random();
		while (rcounter < n){
			if (nrandom>0.5){
				repeatm++;
			}
			else{
				repeatl++;
			}
			nrandom = Math.random();
			rcounter++;
		}
		double ratio = (double)repeatm / (double)repeatl;
		if (repeatm == 0 || repeatl ==0){
			System.out.println(">  0.5: " + repeatm + " times");
			System.out.println("<= 0.5: " + repeatl + " times");
		}
		else{
			System.out.println(">  0.5: " + repeatm + " times");
			System.out.println("<= 0.5: " + repeatl + " times");
			System.out.println("Ratio:  " + ratio);
		}
	}
}
